title: Bioinformatics Technology Lab
description: Bioinformatics Technology Lab at Canada's Michael Smith Genome Sciences Centre. Primarily interested in de novo genome assembly. More description. 
logo: "/assets/logo.png"

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-relative-links

remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Members: /members
  Publications: /publications
  Projects: /projects
  Software: /software
  
navigation_footer: 
    Alembic by David Darnes: "https://github.com/daviddarnes/alembic"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
    style: compressed # Style compression
    permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
    excerpt_separator: <!-- more --> # Marks end of excerpt in posts
    
  
#collections:
#  posts: 
#    title: Projects
#    output: true
#    description: Ongoing projects
    
